import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { uploadCooperativeFile } from "@/lib/cooperativeData";
import { createGalleryItem, getCurrentMember, getSiteSettings, listApprovedMembers, listGalleryItems, saveSiteSettings, subscribeToLedgerChanges, subscribeToPublicContentChanges, supabase } from "@/lib/supabase";
import MemberAuthDialog from "@/components/MemberAuthDialog";
import AdminApprovalPanel from "@/components/AdminApprovalPanel";
import { ArrowLeft, ArrowRight, BarChart3, Check, CircleDollarSign, FileDown, FileText, Gem, Globe2, ImagePlus, Landmark, LogIn, Mail, Menu, Pencil, Plus, Printer, ShieldCheck, Sparkles, Users, WalletCards, X } from "lucide-react";

const heroImages = [
  { src: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1600&q=85", eyebrow: "আমাদের শক্তি", title: "ঐক্যে গড়ি আগামী দিনের নিরাপদ ভবিষ্যৎ", text: "স্বচ্ছতা, শৃঙ্খলা ও পারস্পরিক সহযোগিতায় সমিতির প্রতিটি সদস্যের স্বপ্নকে আরও কাছে নিয়ে আসি।" },
  { src: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85", eyebrow: "আমাদের অঙ্গীকার", title: "প্রতিটি সঞ্চয় হোক একটি নতুন সম্ভাবনা", text: "সদস্যদের সঞ্চয় ও অংশগ্রহণকে দায়িত্বশীল ব্যবস্থাপনায় রূপ দিয়ে টেকসই উন্নয়নের পথে এগিয়ে চলি।" },
  { src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&q=85", eyebrow: "আমাদের পরিবার", title: "আঁরা বিয়াক্কুন এক পরিবার", text: "একসঙ্গে সিদ্ধান্ত, একসঙ্গে অগ্রগতি—সমিতির প্রতিটি সদস্যই আমাদের পরিবারের গুরুত্বপূর্ণ অংশ।" },
];



export default function Home() {
  const { user, isAuthenticated } = useAuth();
  const [slide, setSlide] = useState(0);
  const [active, setActive] = useState("home");
  const [mobileNav, setMobileNav] = useState(false);
  const [cmsOpen, setCmsOpen] = useState(false);
  const [siteName, setSiteName] = useState("সমিতি-নাইন্টি ত্রি");
  const [tagline, setTagline] = useState("আঁরা বিয়াক্কুন এক পরিবার");
  const [tagline2, setTagline2] = useState("লক্ষ্য অর্জনে প্রতিজ্ঞাবদ্ধ");
  const [contactEmail, setContactEmail] = useState("shomity39@gmial.com");
  const [saved, setSaved] = useState(false);
  const [cmsNotice, setCmsNotice] = useState("সঞ্চয়, সহযোগিতা ও স্বচ্ছতার মাধ্যমে একটি নিরাপদ সম্মিলিত ভবিষ্যৎ গড়ার অঙ্গীকার।");
  const [logoUrl, setLogoUrl] = useState("");
  const [logoPath, setLogoPath] = useState("");
  const [selectedMember, setSelectedMember] = useState<{ member_id: string; full_name: string; phone?: string | null; photo_url?: string | null } | null>(null);
  const [gallery, setGallery] = useState(heroImages);
  const [liveTick, setLiveTick] = useState(0);
  const [members, setMembers] = useState<Array<{ member_id: string; full_name: string; phone?: string | null; photo_url?: string | null }>>([]);
  const [currentMember, setCurrentMember] = useState<{ full_name?: string; role?: string; status?: string } | null>(null);

  useEffect(() => { const timer = window.setInterval(() => setSlide((current) => (current + 1) % gallery.length), 5000); return () => window.clearInterval(timer); }, [gallery.length]);
  useEffect(() => { let cleanup: (() => void) | undefined; void subscribeToLedgerChanges(() => { setLiveTick((tick) => tick + 1); void listApprovedMembers().then(setMembers).catch(() => undefined); }).then((unsubscribe) => { cleanup = unsubscribe; }); void listApprovedMembers().then(setMembers).catch(() => undefined); return () => cleanup?.(); }, []);
  useEffect(() => { const refreshMember = () => { void getCurrentMember().then(setCurrentMember).catch(() => setCurrentMember(null)); }; refreshMember(); window.addEventListener("supabase-session-changed", refreshMember); return () => window.removeEventListener("supabase-session-changed", refreshMember); }, []);
  useEffect(() => { let cleanup: (() => void) | undefined; const loadPublicContent = async () => { const [settings, liveGallery] = await Promise.all([getSiteSettings(), listGalleryItems()]); if (settings) { setSiteName(settings.name || "সমিতি-নাইন্টি ত্রি"); setTagline(settings.tagline_one || "আঁরা বিয়াক্কুন এক পরিবার"); setTagline2(settings.tagline_two || "লক্ষ্য অর্জনে প্রতিজ্ঞাবদ্ধ"); setContactEmail(settings.contact_email || "shomity39@gmial.com"); if ("notice_text" in settings && typeof settings.notice_text === "string" && settings.notice_text) setCmsNotice(settings.notice_text); if ("logo_url" in settings && typeof settings.logo_url === "string") setLogoUrl(settings.logo_url); if ("logo_path" in settings && typeof settings.logo_path === "string") setLogoPath(settings.logo_path); } if (liveGallery.length) setGallery(liveGallery); }; void loadPublicContent().catch(() => undefined); void subscribeToPublicContentChanges(() => { void loadPublicContent().catch(() => undefined); }).then((unsubscribe) => { cleanup = unsubscribe; }); return () => cleanup?.(); }, []);
  const currentHero = gallery[slide] ?? heroImages[0];
  const userLabel = currentMember?.full_name ?? user?.name ?? "অতিথি সদস্য";
  const navItems = [{ id: "home", label: "হোম" }, { id: "about", label: "আমাদের সম্পর্কে" }, { id: "members", label: "সদস্যবৃন্দ" }, { id: "hisab", label: "হিসাব ব্যবস্থাপনা" }];
  const visibleMembers = members;

  const saveCms = async () => { try { await saveSiteSettings({ name: siteName, taglineOne: tagline, taglineTwo: tagline2, contactEmail, noticeText: cmsNotice, logoUrl, logoPath }); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } catch { setSaved(false); } };
  const onLogoUpload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const uploaded = await uploadCooperativeFile(file, "branding"); setLogoUrl(uploaded.url); setLogoPath(uploaded.path); };
  const onGalleryUpload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const uploaded = await uploadCooperativeFile(file, "gallery"); const title = file.name.replace(/\.[^/.]+$/, ""); if (supabase) await createGalleryItem({ imageUrl: uploaded.url, storagePath: uploaded.path, title, sortOrder: gallery.length }); setGallery((items) => [...items, { id: `local-${Date.now()}`, src: uploaded.url, eyebrow: "নতুন গ্যালারি", title, text: "অ্যাডমিন প্যানেল থেকে যোগ করা নতুন গ্যালারি কনটেন্ট।", sort_order: gallery.length } as typeof items[number]]); };

  return <div className="site-shell" dir="rtl"><header className="public-nav"><div className="container nav-inner"><a className="brand" href="#home" onClick={() => setActive("home")}><span className="brand-mark">{logoUrl ? <img src={logoUrl} alt={`${siteName} লোগো`} className="h-full w-full rounded-[12px] object-cover" /> : <Gem className="h-5 w-5" />}</span><span><strong>{siteName}</strong><small>আঁরা বিয়াক্কুন এক পরিবার, লক্ষ্য অর্জনে প্রতিজ্ঞাবদ্ধ</small></span></a><nav className={`desktop-links ${mobileNav ? "is-open" : ""}`}>{navItems.map((item) => <a key={item.id} className={active === item.id ? "active" : ""} href={item.id === "hisab" ? "/hisab" : `#${item.id}`} onClick={() => { setActive(item.id); setMobileNav(false); }}>{item.label}</a>)}</nav><div className="nav-actions"><Badge className="live-badge"><span />লাইভ আপডেট{liveTick > 0 ? ` · ${liveTick}` : ""}</Badge>{currentMember?.role === "admin" && <Button variant="outline" size="sm" onClick={() => setCmsOpen(true)}><Pencil className="mr-2 h-4 w-4" />এডমিন প্যানেল</Button>}{currentMember ? <span className="user-chip">{userLabel}</span> : <MemberAuthDialog />}<Button variant="ghost" size="icon" className="mobile-menu" onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X /> : <Menu />}</Button></div></div></header>

    <main id="home"><section className="hero"><div key={`${currentHero.src}-${slide}`} className="hero-image hero-swipe" style={{ backgroundImage: `linear-gradient(90deg, rgba(8,25,40,.82) 0%, rgba(8,25,40,.58) 42%, rgba(8,25,40,.1) 100%), url(${currentHero.src})` }} /><div className="container hero-content"><div className="hero-copy"><span className="hero-kicker"><Sparkles className="h-4 w-4" /> {currentHero.eyebrow}</span><h1>{currentHero.title}</h1><p>{currentHero.text}</p><div className="hero-ctas"><Button className="cta-primary" onClick={() => { window.location.href = "/hisab"; }}>হিসাব ব্যবস্থাপনায় প্রবেশ <ArrowRight className="ml-2 h-4 w-4" /></Button><Button variant="outline" className="cta-ghost" onClick={() => { setActive("about"); document.getElementById("about")?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>আরও জানুন</Button></div></div><div className="hero-side-note"><span>০{slide + 1}</span><div className="hero-progress"><i style={{ width: `${((slide + 1) / gallery.length) * 100}%` }} /></div><span>০{gallery.length}</span></div></div><div className="hero-controls"><Button variant="ghost" size="icon" onClick={() => setSlide((slide - 1 + gallery.length) % gallery.length)}><ArrowLeft /></Button><Button variant="ghost" size="icon" onClick={() => setSlide((slide + 1) % gallery.length)}><ArrowRight /></Button></div></section>

    <section className="trust-strip"><div className="container trust-inner"><div><ShieldCheck className="h-5 w-5" /><span>স্বচ্ছ হিসাবরক্ষণ</span></div><div><Globe2 className="h-5 w-5" /><span>সবার জন্য উন্মুক্ত</span></div><div><Users className="h-5 w-5" /><span>৪৮ সক্রিয় সদস্য</span></div><div><BarChart3 className="h-5 w-5" /><span>তাৎক্ষণিক আপডেট</span></div></div></section>

    <section className="section access-teaser"><div className="container"><div className="access-teaser-card"><div><p className="eyebrow">নিরাপদ সদস্য অঞ্চল</p><h2>হিসাব ব্যবস্থাপনা আলাদা ও সুরক্ষিত</h2><p>সমিতির জমা, খরচ, সদস্যভিত্তিক হিসাব ও রিপোর্ট দেখতে অনুমোদিত সদস্য হিসেবে প্রবেশ করুন। সবার জন্য উন্মুক্ত হোমপেজে কোনো আর্থিক তথ্য প্রকাশ করা হয় না।</p></div><Button className="cta-primary" onClick={() => { window.location.href = "/hisab"; }}>সুরক্ষিত অংশে প্রবেশ <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></section>

    

    <section id="about" className="section about-section"><div className="container about-grid"><div><p className="eyebrow">আমাদের পরিচয়</p><h2>লক্ষ্য অর্জনে প্রতিজ্ঞাবদ্ধ</h2><p className="lead">{tagline} · {tagline2}—এই বিশ্বাসকে সামনে রেখে সমিতি-নাইন্টি ত্রি সদস্যদের সঞ্চয়, সহযোগিতা ও সম্মিলিত উদ্যোগকে একটি নিরাপদ কাঠামোয় নিয়ে আসে।</p><div className="pillars"><div><span>০১</span><strong>দায়িত্বশীলতা</strong><p>প্রতিটি সিদ্ধান্তে সদস্যদের স্বার্থ অগ্রাধিকার পায়।</p></div><div><span>০২</span><strong>সহযোগিতা</strong><p>সম্মিলিত উদ্যোগেই তৈরি হয় দীর্ঘস্থায়ী পরিবর্তন।</p></div><div><span>০৩</span><strong>স্বচ্ছতা</strong><p>প্রতিটি হিসাব সদস্যদের দেখার ও বোঝার অধিকার রয়েছে।</p></div></div></div><div className="about-card"><div className="about-card-top"><span>২০২৬</span><span className="about-logo-mark">{logoUrl ? <img src={logoUrl} alt={`${siteName} লোগো`} /> : <Gem />}</span></div><h3>একসঙ্গে এগিয়ে চলি</h3><p>{cmsNotice}</p><Button variant="outline" onClick={() => currentMember?.role === "admin" ? setCmsOpen(true) : window.location.assign("/hisab")}>পরিচালনা ও বার্তা <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></section>

    <section id="members" className="section members-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">আমাদের পরিবার</p><h2>সদস্যদের সম্মিলিত শক্তি</h2></div><Badge variant="outline">সর্বোচ্চ ৫০ সদস্য</Badge></div><div className="member-row">{visibleMembers.length ? visibleMembers.map((member, index) => <button type="button" className="member-card text-right" key={member.member_id} onClick={() => setSelectedMember(member)}><div className={`member-avatar m-${index % 6}`}>{member.photo_url ? <img src={member.photo_url} alt={`${member.full_name} এর ছবি`} className="h-full w-full rounded-full object-cover" /> : member.full_name.slice(0, 2)}</div><strong>{member.full_name}</strong><span>সদস্য · {member.member_id}</span></button>) : <div className="member-empty">এডমিন অনুমোদিত সদস্যদের ছবি ও পরিচয় এখানে প্রদর্শিত হবে।</div>}</div></div></section>
    </main>

    {selectedMember && <div className="cms-overlay" onClick={() => setSelectedMember(null)}><Card className="member-detail-card" onClick={(e) => e.stopPropagation()}><div className="cms-head"><div><p className="eyebrow">সদস্য পরিচিতি</p><h2>{selectedMember.full_name}</h2></div><Button variant="ghost" size="icon" onClick={() => setSelectedMember(null)}><X /></Button></div><div className="member-detail-body"><div className="member-detail-avatar">{selectedMember.photo_url ? <img src={selectedMember.photo_url} alt={`${selectedMember.full_name} এর ছবি`} /> : selectedMember.full_name.slice(0, 2)}</div><p><strong>সদস্য আইডি:</strong> {selectedMember.member_id}</p><p><strong>যোগাযোগ:</strong> {selectedMember.phone || "এডমিন অনুমোদনের পরে তথ্য দেখা যাবে"}</p><p className="text-sm text-slate-500">এই তথ্যটি অনুমোদিত সদস্যদের জন্য প্রদর্শিত হচ্ছে। পরিবর্তনের জন্য এডমিনের সঙ্গে যোগাযোগ করুন।</p></div></Card></div>}

    {cmsOpen && <div className="cms-overlay" onClick={() => setCmsOpen(false)}><Card className="cms-panel" onClick={(e) => e.stopPropagation()}><div className="cms-head"><div><p className="eyebrow">এডমিন প্যানেল</p><h2>সাইট কনটেন্ট সম্পাদনা</h2></div><Button variant="ghost" size="icon" onClick={() => setCmsOpen(false)}><X /></Button></div><div className="cms-form"><AdminApprovalPanel /><div><Label>সমিতির নাম</Label><Input value={siteName} onChange={(e) => setSiteName(e.target.value)} /></div><div><Label>প্রধান ট্যাগলাইন</Label><Input value={tagline} onChange={(e) => setTagline(e.target.value)} /></div><div><Label>দ্বিতীয় ট্যাগলাইন</Label><Input value={tagline2} onChange={(e) => setTagline2(e.target.value)} /></div><div><Label>যোগাযোগের ইমেইল</Label><Input value={contactEmail} onChange={(e) => setContactEmail(e.target.value)} /></div><div><Label>সংক্ষিপ্ত পরিচিতি ও বার্তা</Label><Textarea value={cmsNotice} onChange={(e) => setCmsNotice(e.target.value)} /></div><div className="upload-box"><ImagePlus className="h-5 w-5" /><div><strong>ওয়েবসাইটের লোগো</strong><p>লোগো আপলোড, preview ও পরিবর্তন করুন</p></div><label className="upload-button">লোগো নির্বাচন<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={onLogoUpload} /></label></div><div className="upload-box"><ImagePlus className="h-5 w-5" /><div><strong>গ্যালারি ছবি যোগ করুন</strong><p>ছবি স্বয়ংক্রিয়ভাবে সংকুচিত হয়ে সংরক্ষিত হবে</p></div><label className="upload-button">ফাইল নির্বাচন<input type="file" accept="image/*" onChange={onGalleryUpload} /></label></div><Button onClick={saveCms} className="w-full">{saved ? <><Check className="mr-2 h-4 w-4" />সংরক্ষিত হয়েছে</> : "পরিবর্তন সংরক্ষণ করুন"}</Button></div></Card></div>}
    <a className="floating-mail" href={`mailto:${contactEmail}`} aria-label="ইমেইলে যোগাযোগ"><Mail /></a><footer><div className="container footer-inner"><div className="brand footer-brand"><span className="brand-mark">{logoUrl ? <img src={logoUrl} alt={`${siteName} লোগো`} className="h-full w-full rounded-[12px] object-cover" /> : <Gem className="h-5 w-5" />}</span><span><strong>{siteName}</strong><small>আঁরা বিয়াক্কুন এক পরিবার, লক্ষ্য অর্জনে প্রতিজ্ঞাবদ্ধ</small></span></div><p>© ২০২৬ {siteName} · {tagline}, {tagline2}</p><div className="footer-contact"><Mail className="h-4 w-4" /> {contactEmail}</div></div></footer></div>;
}
