import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createAdminInvite, listApprovedMembers, listPendingInvites, supabase, updateInviteStatus, updateMemberPhoto, uploadMemberPhoto } from "@/lib/supabase";
import { compressUpload } from "@/lib/imageCompression";
import { trpc } from "@/lib/trpc";
import { Check, UserPlus } from "lucide-react";

type Invite = { id: string; email: string; member_id: string; full_name: string; phone: string; status: string };
type Member = { id: string; member_id: string; full_name: string; phone?: string | null; photo_url?: string | null; role?: string | null };

export default function AdminApprovalPanel() {
  const [form, setForm] = useState({ fullName: "", email: "", phone: "", memberId: "" }); const [invites, setInvites] = useState<Invite[]>([]); const [members, setMembers] = useState<Member[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const sendStatusEmail = trpc.notifications.sendMemberStatus.useMutation();
  const notifyMemberStatus = async (input: { email: string; fullName: string; status: "approved" | "suspended"; accessToken: string }) => {
    if (window.location.hostname.endsWith("netlify.app")) {
      const response = await fetch("/.netlify/functions/notify-member-status", { method: "POST", headers: { "content-type": "application/json", Authorization: `Bearer ${input.accessToken}` }, body: JSON.stringify(input) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.message ?? "ইমেইল পাঠানো যায়নি");
      return data as { sent: boolean };
    }
    return sendStatusEmail.mutateAsync(input);
  };
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const refresh = () => { void Promise.all([listPendingInvites(), listApprovedMembers()]).then(([nextInvites, nextMembers]) => { setInvites(nextInvites as Invite[]); setMembers(nextMembers as Member[]); }).catch(() => undefined); };
  useEffect(refresh, []);
  const changeMemberPhoto = async (member: Member, file: File) => { try { setBusy(true); const compressed = await compressUpload(file, "members"); const uploaded = await uploadMemberPhoto(compressed, member.member_id); await updateMemberPhoto(member.id, uploaded); setNotice(`${member.full_name} এর ছবি আপডেট হয়েছে`); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "ছবি আপডেট করা যায়নি"); } finally { setBusy(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setNotice(""); try { await createAdminInvite(form); const sessionResult = await supabase?.auth.getSession(); const accessToken = sessionResult?.data.session?.access_token ?? ""; const emailResult = await notifyMemberStatus({ email: form.email, fullName: form.fullName, status: "approved", accessToken }); setNotice(emailResult.sent ? "সদস্য অনুমোদন ও ইমেইল পাঠানো হয়েছে" : "সদস্য অনুমোদন হয়েছে; ইমেইল কনফিগারেশন অসম্পূর্ণ"); setForm({ fullName: "", email: "", phone: "", memberId: "" }); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "অনুমোদন যোগ করা যায়নি"); } finally { setBusy(false); } };
  const suspend = async (id: string) => { try { await updateInviteStatus(id, "suspended"); const sessionResult = await supabase?.auth.getSession(); const accessToken = sessionResult?.data.session?.access_token ?? ""; const emailResult = await notifyMemberStatus({ email: invites.find((item) => item.id === id)?.email ?? "", fullName: invites.find((item) => item.id === id)?.full_name ?? "সদস্য", status: "suspended", accessToken }); setNotice(emailResult.sent ? "সদস্যের অনুমোদন স্থগিত ও ইমেইল পাঠানো হয়েছে" : "সদস্যের অনুমোদন স্থগিত হয়েছে; ইমেইল কনফিগারেশন অসম্পূর্ণ"); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "অ্যাকশন সম্পন্ন করা যায়নি"); } };
  return <div className="rounded-xl border border-amber-100 bg-amber-50/60 p-4"><div className="mb-3 flex items-center gap-2"><UserPlus className="h-4 w-4 text-amber-700" /><strong className="text-sm text-slate-800">এডমিন সদস্য অনুমোদন</strong></div><form className="grid gap-3" onSubmit={submit}><div><Label>পূর্ণ নাম</Label><Input required value={form.fullName} onChange={(e) => update("fullName", e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><Label>সদস্য আইডি</Label><Input required value={form.memberId} onChange={(e) => update("memberId", e.target.value)} placeholder="S-049" /></div><div><Label>মোবাইল</Label><Input required value={form.phone} onChange={(e) => update("phone", e.target.value)} /></div></div><div><Label>অনুমোদিত ইমেইল</Label><Input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></div><Button type="submit" disabled={busy} className="bg-[#092337]">{busy ? "সংরক্ষণ হচ্ছে…" : "সদস্য অনুমোদন করুন"}</Button></form><div className="mt-4 grid gap-2">{invites.map((invite) => <div key={invite.id} className="flex items-center justify-between gap-3 rounded-lg bg-white p-3 text-xs"><div><strong className="block">{invite.full_name} · {invite.member_id}</strong><span className="text-slate-500">{invite.email} · {invite.status === "approved" ? "অনুমোদিত" : "স্থগিত"}</span></div>{invite.status === "approved" && <Button variant="outline" size="sm" onClick={() => suspend(invite.id)}>স্থগিত করুন</Button>}</div>)}</div><div className="mt-4 rounded-lg border border-slate-100 bg-slate-50 p-3"><strong className="mb-2 block text-sm text-slate-800">সদস্যের প্রোফাইল ছবি</strong><div className="grid gap-2">{members.map((member) => <div key={member.id} className="flex items-center justify-between gap-3 rounded-lg bg-white p-2 text-xs"><div className="flex min-w-0 items-center gap-2"><div className="h-9 w-9 overflow-hidden rounded-full bg-emerald-50 text-center leading-9 text-emerald-700">{member.photo_url ? <img src={member.photo_url} alt={`${member.full_name} এর ছবি`} className="h-full w-full object-cover" /> : member.full_name.slice(0, 2)}</div><span className="truncate">{member.full_name} · {member.member_id}</span></div><label className="cursor-pointer rounded-md border border-slate-200 px-2 py-1"><input className="hidden" type="file" accept="image/*" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void changeMemberPhoto(member, file); event.currentTarget.value = ""; }} />ছবি বদলান</label></div>)}</div></div>{notice && <p className={`mt-3 text-xs ${notice.includes("হয়েছে") || notice.includes("যোগ") ? "text-emerald-700" : "text-rose-700"}`}><Check className="mr-1 inline h-3 w-3" />{notice}</p>}</div>;
}
