import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { uploadCooperativeFile } from "@/lib/cooperativeData";
import type { MemberTransaction } from "@/lib/supabase";

type Member = { id: string; member_id: string; full_name: string };
type Props = { members: Member[]; initial?: MemberTransaction | null; onSubmit: (values: Record<string, unknown>) => Promise<void>; onCancel: () => void };

const labels = { deposit: "জমা", withdrawal: "উইথড্র", fine: "ফাইন", loan: "ধার" } as const;

export default function MemberTransactionForm({ members, initial, onSubmit, onCancel }: Props) {
  const initialMember = Array.isArray(initial?.member) ? initial?.member[0] : initial?.member;
  const [values, setValues] = useState({ member_id: initial?.member_id ?? initialMember?.id ?? "", transaction_date: initial?.transaction_date ?? new Date().toISOString().slice(0, 10), transaction_type: initial?.transaction_type ?? "deposit", description: initial?.description ?? "", amount: initial ? String(initial.amount) : "", payment_method: initial?.payment_method ?? "cash", attachment_url: initial?.attachment_url ?? "", attachment_name: initial?.attachment_name ?? "", attachment_type: initial?.attachment_type ?? "", attachment_size: initial?.attachment_size ? String(initial.attachment_size) : "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const upload = async (file?: File) => { if (!file) return; try { const uploaded = await uploadCooperativeFile(file, "receipts"); set("attachment_url", uploaded.url); set("attachment_name", uploaded.compressed.name); set("attachment_type", uploaded.compressed.type || "ফাইল"); set("attachment_size", String(Math.max(1, Math.round(uploaded.compressed.size / 1024)))); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "ফাইল আপলোড করা যায়নি"); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!values.member_id) return setError("সদস্য নির্বাচন করুন"); if (!values.description.trim()) return setError("বিবরণ লিখুন"); if (!values.amount || Number(values.amount) <= 0) return setError("সঠিক পরিমাণ লিখুন"); setBusy(true); setError(""); try { await onSubmit({ id: initial?.id, member_id: values.member_id, transaction_date: values.transaction_date, transaction_type: values.transaction_type, description: values.description.trim(), amount: Number(values.amount), payment_method: values.payment_method, attachment_url: values.attachment_url || null, attachment_name: values.attachment_name || null, attachment_type: values.attachment_type || null, attachment_size: values.attachment_size ? Number(values.attachment_size) : null }); } catch (err) { setError(err instanceof Error ? err.message : "সংরক্ষণ করা যায়নি"); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={(open) => !open && onCancel()}><DialogContent className="max-h-[90vh] overflow-y-auto bg-white text-slate-900"><DialogHeader><DialogTitle>{initial ? "সদস্যের হিসাব সম্পাদনা" : "সদস্যের নতুন হিসাব"}</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submit}><div><Label>সদস্য</Label><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={values.member_id} onChange={(event) => set("member_id", event.target.value)} required><option value="">সদস্য নির্বাচন করুন</option>{members.map((member) => <option key={member.id} value={member.id}>{member.full_name} · {member.member_id}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><Label>হিসাবের ধরন</Label><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={values.transaction_type} onChange={(event) => set("transaction_type", event.target.value)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><Label>তারিখ</Label><Input type="date" value={values.transaction_date} onChange={(event) => set("transaction_date", event.target.value)} required /></div></div><div><Label>বিবরণ</Label><Textarea value={values.description} onChange={(event) => set("description", event.target.value)} placeholder="যেমন: মার্চ মাসের জমা" required /></div><div className="grid grid-cols-2 gap-3"><div><Label>পরিমাণ</Label><Input type="number" min="0.01" step="0.01" value={values.amount} onChange={(event) => set("amount", event.target.value)} required /></div><div><Label>পেমেন্ট মাধ্যম</Label><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={values.payment_method} onChange={(event) => set("payment_method", event.target.value)}><option value="cash">নগদ</option><option value="bkash">বিকাশ</option><option value="bank">ব্যাংক</option><option value="other">অন্যান্য</option></select></div></div><div><Label>রসিদ/প্রমাণপত্র</Label><Input type="file" accept="image/*,application/pdf" onChange={(event) => void upload(event.target.files?.[0])} />{values.attachment_url && <p className="mt-1 text-xs text-emerald-700">ফাইল প্রস্তুত: {values.attachment_name} · {values.attachment_size} KB</p>}</div>{error && <p className="rounded-md bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="flex gap-2"><Button type="submit" disabled={busy}>{busy ? "সংরক্ষণ হচ্ছে…" : "সংরক্ষণ করুন"}</Button><Button type="button" variant="outline" onClick={onCancel}>বাতিল</Button></div></form></DialogContent></Dialog>;
}
